trigger:
- master

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  imageName: gkama/aiof-portal
  tag: latest

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: docker build and push
      inputs:
        containerRegistry: gkama-docker-cr
        repository: $(image)
        command: build
        Dockerfile: $(Build.SourcesDirectory)/Dockerfile
        tags: |
          $(tag)

    - task: Docker@2
      displayName: docker save
      inputs:
        containerRegistry: gkama-docker-cr
        repository: $(image)
        command: save
        arguments: --output $(Build.SourcesDirectory)/aiof-portal-image.image.tar $(image):$(tag)

    - task: ArchiveFiles@2
      displayName: archive
      inputs:
        rootFolderOrFile: $(Build.SourcesDirectory)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.SourcesDirectory)/publish/aiof-portal-$(Build.BuildId).zip
        replaceExistingArchive: false

    - task: PublishBuildArtifacts@1
      displayName: publish artifacts
      inputs:
        pathtoPublish: $(Build.SourcesDirectory)/publish/aiof-portal-$(Build.BuildId).zip
        artifactName: aiof-portal
        publishLocation: Container