version: "3.7"

services:
  aiofdata:
    image: gkama/aiof-data:latest
    container_name: aiof-data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: aiof
      POSTGRES_PASSWORD: aiofiscool
      POSTGRES_DB: aiof

  aiofauth:
    image: gkama/aiof-auth:latest
    container_name: aiof-auth
    depends_on:
      - aiofdata
    ports:
      - 8001:80
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      Data__PostgreSQL: Server=aiofdata;Port=5432;Database=aiof;User Id=aiof;Password=aiofiscool;
  
  aiofapi:
    image: gkama/aiof-api:latest
    container_name: aiof-api
    depends_on:
      - aiofdata
      - aiofauth
    ports:
      - 8000:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Data__PostgreSQL: Server=aiofdata;Port=5432;Database=aiof;User Id=aiof;Password=aiofiscool;

  aiofmetadata:
    image: gkama/aiof-metadata:latest
    container_name: aiof-metadata
    ports:
      - 8002:80