name: release

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        required: true
        default: dev

jobs:
  release:
    environment: ${{ github.event.inputs.env }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: docker buildx
      uses: docker/setup-buildx-action@v1

    - name: docker login
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gkama/aiof-portal:latest

    - name: az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: az webapp restart
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart -n ${{ secrets.AZURE_APP_NAME }} -g ${{ secrets.AZURE_APP_RESOURCE_GROUP }}